name: run-tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U --upgrade-strategy=eager --pre -e .[testing]
          pip install coverage
      - name: Set up Minio
        run: |
          wget https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x minio
          sudo mv minio /usr/local/bin

          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin

          export MINIO_ACCESS_KEY="minio_access_key"
          export MINIO_SECRET_KEY="minio_secret_key"
          minio server /data &
          sleep 10  # Give Minio some time to start

          mc alias set minio http://127.0.0.1:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
          mc mb minio/test-bucket
      - name: Test with unittest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          # Set up environment
          export STORAGE_EMULATOR_HOST="http://127.0.0.1:9000"
          
          coverage run --source depot -m unittest discover -v
          coverage report
      - name: Publish to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install 'coveralls'
          coveralls --service=github